### ISSUE TITLE
When an image is not found we should fetch an alternative

### ISSUE THREAD

**Issue by RcrossF** [RcrossF/BCLiquorBot#2]
Currently when a BC liquor image can't be found or is None we display a generic "not found" image. Instead we could use google/ddg images for a replacement

**Comment by owenjaques** [comment]
I have some working code for this but am waiting for https://github.com/RcrossF/BCLiquorBot/pull/9 to be merged before I open up a PR.

**Comment by owenjaques** [comment]
PR implementing this has been merged.
